"""Add WechatList and WechatArticleList models

Revision ID: 0c8740bb4663
Revises: 28f5b70f7022
Create Date: 2025-09-17 22:33:00.139141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c8740bb4663'
down_revision = '28f5b70f7022'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wechat_article_list',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='公众号文章列表ID'),
    sa.Column('wechat_list_id', sa.Integer(), nullable=True, comment='公众号列表ID'),
    sa.Column('wechat_account_name', sa.String(length=100), nullable=True, comment='公众号名称'),
    sa.Column('article_id', sa.String(length=100), nullable=True, comment='文章ID'),
    sa.Column('article_title', sa.String(length=255), nullable=True, comment='文章标题'),
    sa.Column('article_cover', sa.String(length=500), nullable=True, comment='文章封面'),
    sa.Column('article_link', sa.String(length=500), nullable=True, comment='文章链接'),
    sa.Column('article_author_name', sa.String(length=100), nullable=True, comment='文章作者'),
    sa.Column('article_is_deleted', sa.String(length=10), nullable=True, comment='文章是否删除'),
    sa.Column('is_downloaded', sa.String(length=10), nullable=True, comment='是否已下载'),
    sa.Column('article_create_time', sa.TIMESTAMP(timezone=True), nullable=True, comment='文章创建时间'),
    sa.Column('article_update_time', sa.TIMESTAMP(timezone=True), nullable=True, comment='文章更新时间'),
    sa.Column('create_time', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wechat_list',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='公众号列表ID'),
    sa.Column('wechat_account_name', sa.String(length=100), nullable=False, comment='公众号名称'),
    sa.Column('memo', sa.String(length=200), nullable=True, comment='备注'),
    sa.Column('start_date', sa.Date(), nullable=True, comment='开始日期'),
    sa.Column('end_date', sa.Date(), nullable=True, comment='结束日期'),
    sa.Column('fakeid', sa.String(length=100), nullable=True, comment='公众号唯一标识'),
    sa.Column('token', sa.String(length=100), nullable=True, comment='Token信息'),
    sa.Column('cookie', sa.Text(), nullable=True, comment='Cookie信息'),
    sa.Column('begin', sa.Integer(), nullable=True, comment='起始位置'),
    sa.Column('count', sa.Integer(), nullable=True, comment='采集数量'),
    sa.Column('create_time', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wechat_list')
    op.drop_table('wechat_article_list')
    # ### end Alembic commands ###
