"""Initial migration.

Revision ID: 0d52e52b69ab
Revises: 
Create Date: 2025-09-07 12:27:42.535608

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0d52e52b69ab'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversion_errors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=200), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=200), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('file_created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('file_modified_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('markdown_content', sa.Text(), nullable=True),
    sa.Column('is_converted', sa.Integer(), nullable=True),
    sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_path')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index('idx_documents_file_path', ['file_path'], unique=True)
        batch_op.create_index('idx_documents_search_vector', ['search_vector'], unique=False, postgresql_using='gin')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index('idx_documents_search_vector', postgresql_using='gin')
        batch_op.drop_index('idx_documents_file_path')

    op.drop_table('documents')
    op.drop_table('conversion_errors')
    # ### end Alembic commands ###
