"""Add IngestState table and source fields to Document

Revision ID: 28f5b70f7022
Revises: d02107b4f136
Create Date: 2025-09-14 15:12:30.972533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28f5b70f7022'
down_revision = 'd02107b4f136'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingest_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('scope_key', sa.Text(), nullable=False),
    sa.Column('last_started_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('last_ended_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('last_error_message', sa.Text(), nullable=True),
    sa.Column('cursor_updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('total_files', sa.Integer(), nullable=True),
    sa.Column('processed', sa.Integer(), nullable=True),
    sa.Column('skipped', sa.Integer(), nullable=True),
    sa.Column('errors', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ingest_state', schema=None) as batch_op:
        batch_op.create_index('idx_ingest_state_source_scope', ['source', 'scope_key'], unique=True)

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('source_url', sa.Text(), nullable=True))
        batch_op.drop_index(batch_op.f('idx_documents_file_name_gin'), postgresql_ops={'file_name': 'gin_trgm_ops'}, postgresql_using='gin')
        batch_op.drop_index(batch_op.f('idx_documents_markdown_content_gin'), postgresql_ops={'markdown_content': 'gin_trgm_ops'}, postgresql_using='gin')
        batch_op.drop_index(batch_op.f('idx_pgroonga_markdown_content'), postgresql_using='pgroonga')
        batch_op.create_index(batch_op.f('ix_documents_source'), ['source'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_source'))
        batch_op.create_index(batch_op.f('idx_pgroonga_markdown_content'), ['markdown_content'], unique=False, postgresql_using='pgroonga')
        batch_op.create_index(batch_op.f('idx_documents_markdown_content_gin'), ['markdown_content'], unique=False, postgresql_ops={'markdown_content': 'gin_trgm_ops'}, postgresql_using='gin')
        batch_op.create_index(batch_op.f('idx_documents_file_name_gin'), ['file_name'], unique=False, postgresql_ops={'file_name': 'gin_trgm_ops'}, postgresql_using='gin')
        batch_op.drop_column('source_url')
        batch_op.drop_column('source')

    with op.batch_alter_table('ingest_state', schema=None) as batch_op:
        batch_op.drop_index('idx_ingest_state_source_scope')

    op.drop_table('ingest_state')
    # ### end Alembic commands ###
