"""Initial migration with final schema

Revision ID: d02107b4f136
Revises: 
Create Date: 2025-09-13 19:05:29.097858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd02107b4f136'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=200), nullable=False),
    sa.Column('file_type', sa.String(length=10), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('file_created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('file_modified_time', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('markdown_content', sa.Text(), nullable=True),
    sa.Column('conversion_type', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_path')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index('idx_documents_file_path', ['file_path'], unique=True)

    # Manually add custom indexes
    op.execute("""
        CREATE INDEX idx_documents_file_name_gin ON public.documents USING gin (file_name gin_trgm_ops);
    """)
    op.execute("""
        CREATE INDEX idx_documents_markdown_content_gin ON public.documents USING gin (markdown_content gin_trgm_ops);
    """)
    op.execute("""
        CREATE INDEX idx_pgroonga_markdown_content ON public.documents USING pgroonga (markdown_content);
    """)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('documents')
    # ### end Alembic commands ###
